InvoiceTest/Models/Invoices.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace InvoiceTest.Models
{
    public class Invoices
    {
        public Invoices()
        {
            InvoiceDetails = new List<InvoiceDetails>();
        }
        public int Id { get; set; }
        public string InvoiceNumber { get; set; }
        public DateTime InvoiceDate { get; set; }
        public decimal GrandTotalPrice { get; set; }

        public int CustomerId { get; set; }
        [ForeignKey("CustomerId")]
        public Customers Customer { get; set; }

        public int BranchId { get; set; }
        [ForeignKey("BranchId")]
        public Branches Branch { get; set; }

        public List<InvoiceDetails> InvoiceDetails { get; set; }
    }
}

InvoiceTest/Controllers/InvoicesController.cs
using InvoiceTest.Data.Interfaces;
using InvoiceTest.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InvoiceTest.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly IUnitOfWork _uow;

        public InvoicesController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        // GET: InvoicesController
        public ActionResult Index()
        {

            var Model = new CreateInvoiceVm
            {
                Customers = _uow.Customers.GetCustomers(),
                Branches = _uow.Branches.GetBranches(),
                Items = _uow.Items.GetItems(),
                InvoiceDate=DateTime.Now
                          };

            //Model.Details.Add(new DetailsVm() {DetailId=1 });
            //Model.Details.Add(new DetailsVm() { DetailId = 2 });
            //Model.Details.Add(new DetailsVm() { DetailId = 3 });
            return View(Model);
        }

        public JsonResult GetItems()
        {
            var data = _uow.Items.GetItemsForelect();
             return Json(data);
        }

        // GET: InvoicesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: InvoicesController/Create
        public ActionResult Create()
        {
            return View();
        }

        public IActionResult GetDetails(string InvoiceNumber)
        {
            var Data = _uow.Invoices.GetDetails(InvoiceNumber);
            return PartialView("BodyRows", Data);
        }

        // POST: InvoicesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateInvoiceVm model)
        {
            if (_uow.Invoices.IsInvoiceExist(model.InvoiceNumber))
            {
                _uow.Invoices.CreateDetails(model);
            }
            else
            {
                _uow.Invoices.CreateInvoice(model);
            }
            
            _uow.Save();
            return RedirectToAction(nameof(Index));
        }

        // GET: InvoicesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InvoicesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InvoicesController/Delete/5
        public ActionResult ShowExternals()
        {

            var Model = new CreateInvoiceVm();
            Model.Details.Add(new DetailsVm() { ItemId=1,ItemName="A",Price=5,Quantity=2,Discount=0,Total=10 });
            Model.Details.Add(new DetailsVm() { ItemId = 1, ItemName = "A", Price = 5, Quantity = 2, Discount = 0, Total = 10 });
            Model.Details.Add(new DetailsVm() { ItemId = 1, ItemName = "A", Price = 5, Quantity = 2, Discount = 0, Total = 10 });
            return PartialView("_AddFromExternal", Model);
        }

        // POST: InvoicesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public JsonResult GetItemPrice(int id)
        {
            var Price = _uow.Invoices.GetItemPrice(id);
            return Json(Price);
        
        }

        public JsonResult GetQuantity(int id)
        {
            var Quantity = _uow.Invoices.GetItemQuantity(id);
            return Json(Quantity);
        }



    }
}

InvoiceTest/Views/Invoices/BodyRows.cshtml
@model InvoiceTest.ViewModels.CreateInvoiceVm
@{ 
  
}
 @for (int i = 0; i < Model.Details.Count(); i++)
            {
      
                <tr>
                    <td>
                    <select asp-for="Details[i].ItemId" asp-items="@(new SelectList(Model.Items,"Id","Name"))" class="form-control ItemId">
                        <option>

                        </option>
                    </select>
                    </td>
                    <td>
                        @Html.EditorFor(m => m.Details[i].Price, new { htmlAttributes = new { @class = "form-control Price" } })

                    </td>
                    <td>
                        @Html.EditorFor(m => m.Details[i].Quantity, new { htmlAttributes = new { @class = "form-control Quantity"} })

                    </td>
                    <td>
                        @Html.EditorFor(m => m.Details[i].Discount, new { htmlAttributes = new { @class = "form-control Discount", @placeHolder = "                           %" } })

                    </td>
                    <td>
                        @Html.EditorFor(m => m.Details[i].Total, new { htmlAttributes = new { @class = "form-control Total"}})

                    </td>
                    <td>
                        <button type="button" class="btn btn-danger btn-circle btn-sm deleteBtn">X</button>
                    </td>
                </tr>
            }

InvoiceTest/Views/Invoices/Index.cshtml
@model InvoiceTest.ViewModels.CreateInvoiceVm


@section Styles{

    <link href="~/css/select2.min.css" rel="stylesheet" />
}


<form method="post" asp-controller="Invoices" asp-action="Create">
    @*<input type="hidden" asp-for="GrandTotal" id="grandTotalHidden"/>*@
    <div class="row">
        <div class="col">
            <label>Invoice Number</label>
            <input type="text" class="form-control" asp-for="InvoiceNumber" placeholder="Invoice Number" id="invoiceNumber">
        </div>
        <div class="col">
            <label>Invoice Date</label>
            <input type="datetime" class="form-control datepaker" placeholder="Invoice Date" asp-for="InvoiceDate">
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label>Customer Name</label>
            <select asp-for="CustomerId" asp-items=@(new SelectList(Model.Customers,"Id","Name")) class="form-control">
                <option></option>
            </select>
        </div>
        <div class="col">
            <label>Branch Name</label>
                        <select asp-for="BrancheId" asp-items=@(new SelectList(Model.Branches,"Id","Name")) class="form-control">
                <option>
                </option>
            </select>
        </div>
    </div>
    <br />
    <div>
        <div class="actions">
            <button type="button" class="btn btn-primary" id="addNew">Add Item</button>
            <button type="button" class="btn btn-dark" id="addExternal">Add External Item</button>
        </div>

        <br />
        <br />
        <table class="table" id="mainTable">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(m => m.Details[0].ItemName)</th>
                    <th>@Html.DisplayNameFor(m => m.Details[0].Price)</th>
                    <th>@Html.DisplayNameFor(m => m.Details[0].Quantity)</th>
                    <th>@Html.DisplayNameFor(m => m.Details[0].Discount)</th>
                    <th>@Html.DisplayNameFor(m => m.Details[0].Total)</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="tabBody">
                
                   
            </tbody>
            <tfoot>
                <tr>
                    <th></th>
                    <td></td>
                    <td></td>
                    <td><b>Total Price</b></td>
                    <td><input type="number" asp-for="GrandTotal" readonly id="GrandTotal" class="form-control GrandTotal" name="GrandTotal" ></td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>
    <input type="submit" class="form-control btn btn-primary" value="Save" id="saveBtn"/>
</form>

<div id="modalFormDialog" class="modal fade" role="dialog">
    <div class="modal-dialog" id="modalContent">

    </div>
</div>



@section Scripts{
    <script src="~/js/Row.js"></script>
    <script src="~/js/select2.min.js"></script>
    <script>

        $(function() {

            $('.datepaker').datepicker({
                format: 'mm/dd/yyyy',
                startDate: '-3d'
            });

            $('Select').select2({
                selectOnClose: true
            });

            $('#tabBody').load("Invoices/GetDetails?InvoiceNumber=" + 0);

            


        });

        //$(document).on('click', '#CreatBtn', function () {
        //    alert("Ok");
        //});
        
          
        $('#addExternal').click(function () {

            $.ajax({
                url: "Invoices/ShowExternals",
                method: 'GET',
                success: function (result) {
                    $('#modalContent').html(result);
                    $('#modalFormDialog').modal('show');
                    $('#CreatBtn').click(function () {
                        $.ajax({
                            url: "",
                            method: "GET",
                            success: function (result) {

                            }

                        });
                    });
                  }

            });

        });

       

            $('#invoiceNumber').change(function () {
                var Number = $(this).val();
                $('#tabBody').load("Invoices/GetDetails?InvoiceNumber=" + Number, function () {
                    $('#GrandTotal').val(CalculateGrandTotal());
                });
               
             });



        function CalculateGrandTotal() {
            var grandtotal = 0;

            $('.Total').each(function () {

                grandtotal += +$(this).val();
            });

            return grandtotal;
        }


        $('#tabBody').on('change', 'select', function () {
            var price = $(this).parents('tr').find('.Price');
            $.getJSON("Invoices/GetItemPrice?id="+$(this).val(), function (data) {
                price.val(data);
            });
            
           
        });


        $("#tabBody").on('click', '.deleteBtn', function () {
            if ($(this).parents('#tabBody').find('tr').length > 1) {
                $(this).closest('tr').remove();
                $('#GrandTotal').val(CalculateGrandTotal());
            }
            
            
        });


        $("#tabBody").on('input', '.Quantity', function () {
            var quantity = $(this).val();
            var price = $(this).parents('tr').find('.Price').val();
            var itemId = $(this).parents('tr').find('select').val();
            $.getJSON("Invoices/GetQuantity?id=" + itemId, function (result) {
                if (result < quantity) {
                    alert("Sorry The Available Quantity is " + result);
                    $('#saveBtn').attr('disabled',true);
                }
                else
                {
                    $('#saveBtn').removeAttr('disabled');
                }
            });

            $(this).parents('tr').find('.Total').val(quantity * price);
            $('#GrandTotal').val(CalculateGrandTotal());
          
        });


        $('#tabBody').on('input', '.Discount', function () {
            var Discount = $(this).val();
            var PriceBefore = $(this).parents('tr').find('.Price').val();
            var quantity = $(this).parents('tr').find('.Quantity').val();
            if (Discount != 0) {
                if (Discount >= 100) {
                    $(this).parents('tr').find('.Total').val(0);
                } else {
                    var PriceAfter = PriceBefore * (Discount / 100);
                    var FinalPrice = PriceBefore - PriceAfter;
                    $(this).parents('tr').find('.Total').val(quantity * FinalPrice);
                }

            }
            else {


                $(this).parents('tr').find('.Total').val(quantity * PriceBefore);


            }
            $('#GrandTotal').val(CalculateGrandTotal());
          
        });


        $('#tabBody').on('input', '.Price', function () {
            var price = $(this).val();
            var quantity = $(this).parents('tr').find('.Quantity').val();
            var Discount = $(this).parents('tr').find('.Discount').val()
            if (quantity) {
                if (Discount) {
                    var PriceAfterDiscount = price * (Discount / 100);
                    var FinalPrice = price - PriceAfterDiscount;
                    $(this).parents('tr').find('.Total').val(quantity * FinalPrice);
                }
                else {

                    $(this).parents('tr').find('.Total').val(quantity * price);
                }
            }
            $('#GrandTotal').val(CalculateGrandTotal());
          
        });


        $("#addNew").click(function (e) {
            //Old Code 
            //$("#tabBody").append(addRow($("#tabBody tr").length));
          
            var builder = $(addRow($("#tabBody tr").length));
            let $selector = builder.find("select");
            $.getJSON("Invoices/GetItems", function (result) {
                $.each(result, function (index, itemData) {
                    $($selector).append(`<option value=${itemData.id}>${itemData.name} </option>`);
                });
                $("#tabBody").append(builder);
            });
           
        });




    </script>

}

InvoiceTest/Views/Invoices/_AddFromExternal.cshtml
@model InvoiceTest.ViewModels.CreateInvoiceVm
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
    </div>
    @*using form*@
    <div class="modal-body">

    
            <table class="table" id="mainTable">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.Details[0].ItemName)</th>
                        <th>@Html.DisplayNameFor(m => m.Details[0].Price)</th>
                        <th>@Html.DisplayNameFor(m => m.Details[0].Quantity)</th>
                        <th>@Html.DisplayNameFor(m => m.Details[0].Discount)</th>
                        <th>@Html.DisplayNameFor(m => m.Details[0].Total)</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody id="tab2Body">

                    @for (int i = 0; i < Model.Details.Count(); i++)
                    {
                        <tr>
                            <td>
                                @Html.HiddenFor(m => m.Details[i].ItemId, new { htmlAttributes = new { @class = "form-control ItemId" } })
                                @Html.EditorFor(m => m.Details[i].ItemName, new { htmlAttributes = new { @class = "form-control ItemName" } })
                            </td>
                            <td>
                                @Html.EditorFor(m => m.Details[i].Price, new { htmlAttributes = new { @class = "form-control Price" } })

                            </td>
                            <td>
                                @Html.EditorFor(m => m.Details[i].Quantity, new { htmlAttributes = new { @class = "form-control Quantity" } })

                            </td>
                            <td>
                                @Html.EditorFor(m => m.Details[i].Discount, new { htmlAttributes = new { @class = "form-control Discount", @placeHolder = "                           %" } })

                            </td>
                            <td>
                                @Html.EditorFor(m => m.Details[i].Total, new { htmlAttributes = new { @class = "form-control Total" } })

                            </td>
                            <td>
                               @Html.CheckBox("Checked",false, new { htmlAttributes = new { @class = "form-control Check" } })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        @*<input type="button" value="Create" class="btn btn-default" id="CreatBtn" />*@
        <button type="button" class="btn btn-default"  id="CreatBtn">Create</button>
    </div>
    @*End Using*@
</div>